name: index.js Package

on:
  push:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - run: npm publish ./sample-packages/npm
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.GITHUB_TOKEN }}
